language: node_js
node_js:
  - "11.9.0"
sudo: true

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng test --watch=false --browsers=ChromeHeadless && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - ng build --prod --base-href https://github.com/FAANG/faang-portal-frontend/
