steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push

  - name: 'docker/compose:1.19.0'
    env:
      - GCR_HOSTNAME=$_GCR_HOSTNAME
      - PROJECT_ID=$PROJECT_ID
      - REPO_NAME=$REPO_NAME
      - SERVICE_NAME=$_SERVICE_NAME
      - COMMIT_SHA=$COMMIT_SHA
    args:
      - '-f'
      - docker-compose.ci.yml
      - up
      - '-d'
      - '--build'
    id: docker-compose
    waitFor:
      - Push

  - name: 'docker/compose:1.19.0'
    env:
      - GCR_HOSTNAME=$_GCR_HOSTNAME
      - PROJECT_ID=$PROJECT_ID
      - REPO_NAME=$REPO_NAME
      - SERVICE_NAME=$_SERVICE_NAME
      - COMMIT_SHA=$COMMIT_SHA
    args:
      - '-f'
      - docker-compose.ci.yml
      - run
      - cypress
      - ./node_modules/.bin/cypress
      - run
      - '--config'
      - 'baseUrl=http://127.0.0.1'
      - '--browser'
      - chrome
    id: cypress-e2e-tests
    waitFor:
      - docker-compose

  - name: 'docker/compose:1.19.0'
    env:
      - GCR_HOSTNAME=$_GCR_HOSTNAME
      - PROJECT_ID=$PROJECT_ID
      - REPO_NAME=$REPO_NAME
      - SERVICE_NAME=$_SERVICE_NAME
      - COMMIT_SHA=$COMMIT_SHA
    args:
      - '-f'
      - docker-compose.ci.yml
      - down
    id: docker-compose-down
    waitFor:
      - cypress-e2e-tests

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    waitFor:
      - cypress-e2e-tests
    entrypoint: gcloud

timeout: 6600s

images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DEPLOY_REGION: europe-west1
  _GCR_HOSTNAME: eu.gcr.io
  _PLATFORM: managed
  _LABELS: gcb-trigger-id=c87b919f-3804-45b5-a3fb-0c2766a1e1fb
  _TRIGGER_ID: c87b919f-3804-45b5-a3fb-0c2766a1e1fb
  _SERVICE_NAME: faang-portal-frontend
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - faang-portal-frontend
