export const protocolNames = {
  experimentalProtocol: 'Experimental protocol',
  extractionProtocol: 'Extraction protocol',
  rnaPreparation3AdapterLigationProtocol: "Rna preparation 3' adapter ligation protocol",
  rnaPreparation5AdapterLigationProtocol: "Rna preparation 5' adapter ligation protocol",
  libraryGenerationPcrProductIsolationProtocol: 'Library generation PCR product isolation protocol',
  preparationReverseTranscriptionProtocol: 'Preparation reverse transcription protocol',
  libraryGenerationProtocol: 'Library generation protocol',
  bisulfiteConversionProtocol: 'Bisulfite conversion protocol',
  pcrProductIsolationProtocol: 'PCR product isolation protocol',
  transposaseProtocol: 'Transposase protocol',
  dnaseProtocol: 'DNase protocol',
  chipProtocol: 'ChIP protocol',
  'hi-cProtocol': 'Hi-C protocol',
};
