name: Test and Build Project
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/cache@v1
      with:
        path: ~/node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Build
      run: |
        npm install
        ng test --watch=false --browsers=ChromeHeadless && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
        ng build
